#!/bin/sh
modprobe nf_conntrack_pptp
modprobe nf_conntrack_proto_gre
mknod /dev/ppp c 108 0
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE                             
iptables -t nat -A POSTROUTING -s 192.168.4.0/24 -o eth0 -j MASQUERADE           
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT                 
iptables -A INPUT -p icmp -j ACCEPT                                              
iptables -A INPUT -i lo -j ACCEPT                                                
iptables -A INPUT -p tcp -m tcp --dport 1723 -j ACCEPT                           
iptables -A INPUT -p tcp -m tcp --dport 47 -j ACCEPT                             
iptables -A INPUT -p gre -j ACCEPT                                               
iptables -A FORWARD -s 192.168.4.0/24 -i ppp+ -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j TCPMSS --set-mss 1300
iptables -A FORWARD -j ACCEPT                                                    
service iptables save
service iptables start
/usr/sbin/pptpd -f
